# Generated by Django 2.0.7 on 2019-10-28 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20191028_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTopic',
            fields=[
                ('topic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='post.Topic')),
                ('category', models.CharField(help_text='类别', max_length=32)),
            ],
            options={
                'ordering': ['-created_time'],
                'abstract': False,
            },
            bases=('post.topic',),
        ),
    ]
