# Generated by Django 2.0.7 on 2019-10-28 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_categorytopic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
        migrations.RemoveField(
            model_name='categorytopic',
            name='topic_ptr',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='CategoryTopic',
        ),
    ]
